repos:
  - repo: local
    hooks:
      - id: python-formatting
        name: python-formatting
        entry: python -m poetry run black --check mpcforces_extractor
        language: system
        types: [python]

      - id: python-linting
        name: python-linting
        entry: python -m poetry run pylint mpcforces_extractor
        language: system
        types: [python]

      - id: python-testing
        name: python-testing
        entry: poetry run pytest --cov=mpcforces_extractor --cov-report=html
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
