version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - poetry install
      - poetry run pre-commit install

  format:
    desc: Format the code
    cmds:
      - python -m poetry run black spcforces_tools

  lint:
    desc: Lint the code
    cmds:
      - python -m poetry run black --check spcforces_tools
      - |
        python -m poetry run flake8 spcforces_tools \
           --show-source \
           --statistics \
           --count
      - python -m poetry run pylint spcforces_tools

  test:
    desc: Run tests
    cmds:
      - >
        python -m poetry run pytest 
        --cov=spcforces_tools 
        --cov-report=html

  run:
    desc: Run the application
    cmds:
      - poetry run python -m spcforces_tools.mpc_tools
