version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - poetry install
      - poetry run pre-commit install

  format:
    desc: Format the code
    cmds:
      - python -m poetry run black mpcforces_tools

  lint:
    desc: Lint the code
    cmds:
      - python -m poetry run black --check mpcforces_tools
      - |
        python -m poetry run flake8 mpcforces_tools \
           --show-source \
           --statistics \
           --count
      - python -m poetry run pylint mpcforces_tools

  test:
    desc: Run tests
    cmds:
      - >
        python -m poetry run pytest 
        --cov=mpcforces_tools 
        --cov-report=html

  run:
    desc: Run the application
    cmds:
      - poetry run python -m mpcforces_tools.mpc_tools
